// This file is automatically generated. Do not modify it manually.

package plugin

var manifest = struct {
	Id      string
	Version string
}{
	Id:      "com.github.lugamuga.mattermost-yandex-calendar-plugin",
	Version: "0.1.0",
}
