// This file is automatically generated. Do not modify it manually.

package plugin

//nolint:golint,unused
var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.github.lugamuga.mattermost-yandex-calendar-plugin",
	Version: "0.6.5",
}
